#ifndef _statistics_h_INCLUDED
#define _statistics_h_INCLUDED

// clang-format off

//           NAME,            VERBOSITY (0-3), REFERENCE, PRINT, OTHER
//      length 21,  (Always/!0/verbose/never), (relative/percent/MACRO)
#define CADICAL_STATISTICS \
\
  STATISTIC (backbone_phases,        1, INTERVAL, "",    interval) \
  STATISTIC (backbone_probes,        1, percent,  "%",   vars) \
  STATISTIC (backbone_rounds,        2, relative, "per", backbone_phases) \
  STATISTIC (backbone_units,         1, relative, "per", backbone_phases) \
  STATISTIC (backtracked,            3, NOTHING,  0, 0) \
  STATISTIC (blocked,                1, percent,  "%",   clause_added_irr) \
  STATISTIC (blocked_candidates,     2, relative, "per", blockings) \
  STATISTIC (blocked_pure_clauses,   2, percent,  "per", blocked_pure_literals) \
  STATISTIC (blocked_pure_literals,  2, percent,  "%",   vars) \
  STATISTIC (blocked_resolutions,    2, relative, "per", blocked_candidates) \
  STATISTIC (blockings,              1, INTERVAL, "", interval) \
  STATISTIC (clause_added_irr,       2, percent,  "%",  clause_added_total) \
  STATISTIC (clause_added_red,       2, percent,  "%",  clause_added_total) \
  STATISTIC (clause_added_total,     2, relative, "per", searches) \
  STATISTIC (clause_current_irr,     3, NOTHING,  0, 0) \
  STATISTIC (clause_current_red,     3, NOTHING,  0, 0) \
  STATISTIC (clause_current_total,   3, NOTHING,  0, 0) \
  STATISTIC (clause_improved_glue,   2, relative, "per", clause_added_red) \
  STATISTIC (clause_promoted_tier1,  2, relative, "per", clause_improved_glue) \
  STATISTIC (clause_promoted_tier2,  2, relative, "per", clause_improved_glue) \
  STATISTIC (clause_recompute_glue,  2, relative, "per", clause_added_red) \
  STATISTIC (collected,              1, relative, "per", collections) \
  STATISTIC (collections,            1, INTERVAL, "", interval) \
  STATISTIC (compacts,               1, INTERVAL, "per", interval) \
  STATISTIC (condition_active,       2, relative, "per", conditionings) \
  STATISTIC (condition_candidates,   2, relative, "per", conditionings) \
  STATISTIC (conditioned,            1, percent, "%",  clause_added_irr) \
  STATISTIC (conditioned_assign,     2, relative, "per", conditioned) \
  STATISTIC (conditioned_autarky,    2, relative, "per", conditioned) \
  STATISTIC (conditioned_cond,       2, relative, "per", conditioned) \
  STATISTIC (conditioned_initial,    2, relative, "per", conditioned) \
  STATISTIC (conditionings,          1, INTERVAL, "", interval) \
  STATISTIC (condition_pre_assign,   2, relative, "per", conditionings) \
  STATISTIC (condition_pre_autarky,  2, relative, "per", conditionings) \
  STATISTIC (condition_pre_cond,     2, relative, "per", conditionings) \
  STATISTIC (condition_propagated,   2, relative, "per", conditionings) \
  STATISTIC (conflicts,              0, SECONDS, "per",  second) \
  STATISTIC (conflicts_chrono,       2, relative, "per", conflicts) \
  STATISTIC (congruence_ands,        2, relative, "per", congruent) \
  STATISTIC (congruence_dummy_ands,  2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_gates,       2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_gates_and,   2, relative, "%", congruence_gates) \
  STATISTIC (congruence_gates_ite,   2, relative, "%", congruence_gates) \
  STATISTIC (congruence_gates_xor,   2, relative, "%", congruence_gates) \
  STATISTIC (congruence_ites,        2, relative, "%", congruent) \
  STATISTIC (congruence_rounds,      1, INTERVAL, "", interval) \
  STATISTIC (congruence_rw_ands,     2, relative, "per", congruence_gates) \
  STATISTIC (congruence_rw_ites,     2, relative, "per", congruence_gates) \
  STATISTIC (congruence_rw_xors,     2, relative, "per", congruence_gates) \
  STATISTIC (congruence_simp_ands,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_simp_ites,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_simplified,  2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_simp_xors,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_subsumed,    2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_trite,       2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_unary,       2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_unary_and,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_unary_ite,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_units,       2, relative, "per", congruent) \
  STATISTIC (congruence_xors,        2, relative, "per", congruent) \
  STATISTIC (congruent,              1, relative, "per", congruence_rounds) \
  STATISTIC (cover_asymmetric,       2, percent, "%",  cover_total) \
  STATISTIC (cover_blocked,          2, percent, "%",  cover_total) \
  STATISTIC (coverings,              2, INTERVAL, "", interval) \
  STATISTIC (cover_total,            1, percent, "%",  clause_added_irr) \
  STATISTIC (decision_random,        2, percent, "%",  decisions) \
  STATISTIC (decision_random_phase,  2, INTERVAL, "", interval) \
  STATISTIC (decisions,              0, SECONDS, "per",  second) \
  STATISTIC (decision_searched,      2, relative, "per", decisions) \
  STATISTIC (decompositions,         1, INTERVAL, "", interval) \
  STATISTIC (deduplicated,           1, percent, "%",  subsumed) \
  STATISTIC (deduplicate_init,       2, percent, "%",  subsumed) \
  STATISTIC (deduplicate_rounds,     2, relative, "per", searches) \
  STATISTIC (deduplicate_unary,      2, relative, "per", deduplications) \
  STATISTIC (deduplications,         1, INTERVAL, "", interval) \
  STATISTIC (eager_subsumed,         1, percent, "%",  subsumed) \
  STATISTIC (eager_subsumptions,     2, relative, "per", eager_subsumed) \
  STATISTIC (eliminate_and,          2, percent, "%", eliminate_gates) \
  STATISTIC (eliminate_complete,     2, percent, "%", eliminations) \
  STATISTIC (eliminated,             1, percent, "%",  vars) \
  STATISTIC (eliminated_and,         2, percent, "%",  eliminated) \
  STATISTIC (eliminated_defs,        2, percent, "%",  eliminated) \
  STATISTIC (eliminate_def_check,    2, relative, "per", eliminated_defs) \
  STATISTIC (eliminate_def_success,  2, relative, "per", eliminate_def_success) \
  STATISTIC (eliminate_def_ticks,    2, percent, "%",  ticks) \
  STATISTIC (eliminate_def_unit,     2, relative, "per", eliminate_def_check) \
  STATISTIC (eliminated_equivalent,  2, percent, "%",  eliminated) \
  STATISTIC (eliminated_ite,         2, percent, "%",  eliminated) \
  STATISTIC (eliminated_xor,         2, percent, "%",  eliminated) \
  STATISTIC (eliminate_equivalence,  2, relative, "per", propagations) \
  STATISTIC (eliminate_fast_phases,  2, relative, "per", eliminate_fast_rounds) \
  STATISTIC (eliminate_fast_rounds,  2, relative, "per", searches) \
  STATISTIC (eliminate_gates,        2, percent, "%",  eliminate_tried) \
  STATISTIC (eliminate_ite,          2, percent, "%",  eliminate_gates) \
  STATISTIC (eliminate_otf_str,      2, percent, "%",  eliminate_tried) \
  STATISTIC (eliminate_otf_sub,      2, percent, "%",  eliminate_tried) \
  STATISTIC (eliminate_phases,       2, relative, "per", eliminations) \
  STATISTIC (eliminate_resolved,     2, relative, "per", eliminated) \
  STATISTIC (eliminate_strength_bw,  2, relative, "per", eliminate_tried) \
  STATISTIC (eliminate_substituted,  2, relative, "per", eliminate_tried) \
  STATISTIC (eliminate_subsumed_bw,  2, relative, "per", eliminate_tried) \
  STATISTIC (eliminate_tried,        2, relative, "per", eliminations) \
  STATISTIC (eliminate_tried_res,    2, relative, "per", eliminate_tried) \
  STATISTIC (eliminate_xor,          2, relative, "per", eliminate_gates) \
  STATISTIC (eliminations,           1, INTERVAL, "", interval) \
  STATISTIC (extended,               1, relative, "per", extensions) \
  STATISTIC (extensions,             1, relative, "per", searches) \
  STATISTIC (factor_added_clauses,   2, relative, "per", propagations) \
  STATISTIC (factor_added_literals,  2, relative, "per", propagations) \
  STATISTIC (factored,               1, relative, "per", propagations) \
  STATISTIC (factored_and,           2, relative, "per", propagations) \
  STATISTIC (factored_eliminated,    2, relative, "per", propagations) \
  STATISTIC (factored_ite,           2, relative, "per", propagations) \
  STATISTIC (factored_xor,           2, relative, "per", propagations) \
  STATISTIC (factorings,             1, INTERVAL, "", interval) \
  STATISTIC (factor_removed_irr,     2, relative, "per", propagations) \
  STATISTIC (factor_removed_lits,    2, relative, "per", propagations) \
  STATISTIC (factor_removed_red,     2, relative, "per", propagations) \
  STATISTIC (failed_literals,        1, relative, "per", propagations) \
  STATISTIC (flush_hyper,            2, relative, "per", propagations) \
  STATISTIC (flushings,              1, relative, "per", propagations) \
  STATISTIC (flush_learned,          1, relative, "per", propagations) \
  STATISTIC (garbage_bytes,          3, relative, "per", propagations) \
  STATISTIC (garbage_clauses,        3, relative, "per", propagations) \
  STATISTIC (garbage_literals,       3, relative, "per", propagations) \
  STATISTIC (hbr_redundant,          2, relative, "per", propagations) \
  STATISTIC (hbrs,                   1, relative, "per", propagations) \
  STATISTIC (hbr_sizes,              2, relative, "per", propagations) \
  STATISTIC (hbr_subsuming,          2, relative, "per", propagations) \
  STATISTIC (ilb_reuse_assumptions,  2, relative, "per", propagations) \
  STATISTIC (ilb_reuse_levels,       2, relative, "per", propagations) \
  STATISTIC (ilb_reuse_literals,     2, relative, "per", propagations) \
  STATISTIC (ilb_success,            1, relative, "per", propagations) \
  STATISTIC (ilb_triggers,           2, relative, "per", propagations) \
  STATISTIC (incremental_decay,      1, relative, "per", propagations) \
  STATISTIC (inprobingphases,        1, relative, "per", propagations) \
  STATISTIC (inprobingsuccess,       1, relative, "per", propagations) \
  STATISTIC (instantiated,           1, relative, "per", propagations) \
  STATISTIC (instantiate_tried,      2, relative, "per", propagations) \
  STATISTIC (instantiations,         1, relative, "per", propagations) \
  STATISTIC (irredundant_literals,   3, relative, "per", propagations) \
  STATISTIC (learned_binaries,       2, relative, "per", propagations) \
  STATISTIC (learned_clauses,        2, relative, "per", propagations) \
  STATISTIC (learned_literals,       2, relative, "per", propagations) \
  STATISTIC (learned_units,          2, relative, "per", propagations) \
  STATISTIC (lucky,                  1, relative, "per", propagations) \
  STATISTIC (lucky_backward_one,     2, relative, "per", propagations) \
  STATISTIC (lucky_backward_zero,    2, relative, "per", propagations) \
  STATISTIC (lucky_constant_one,     2, relative, "per", propagations) \
  STATISTIC (lucky_constant_zero,    2, relative, "per", propagations) \
  STATISTIC (lucky_forward_one,      2, relative, "per", propagations) \
  STATISTIC (lucky_forward_zero,     2, relative, "per", propagations) \
  STATISTIC (lucky_random,           2, relative, "per", propagations) \
  STATISTIC (lucky_tried,            2, relative, "per", propagations) \
  STATISTIC (lucky_units,            2, relative, "per", propagations) \
  STATISTIC (mark_block,             3, relative, "per", propagations) \
  STATISTIC (mark_elim,              3, relative, "per", propagations) \
  STATISTIC (mark_factor,            3, relative, "per", propagations) \
  STATISTIC (mark_subsume,           3, relative, "per", propagations) \
  STATISTIC (mark_ternary,           3, relative, "per", propagations) \
  STATISTIC (minimized,              1, relative, "per", propagations) \
  STATISTIC (otfs_strengthened,      1, relative, "per", propagations) \
  STATISTIC (otfs_subsumed,          1, relative, "per", propagations) \
  STATISTIC (preprocessings,         2, relative, "per", propagations) \
  STATISTIC (probed,                 1, relative, "per", propagations) \
  STATISTIC (probe_failed_literals,  1, relative, "per", propagations) \
  STATISTIC (probingrounds,          2, relative, "per", propagations) \
  STATISTIC (propagations,           0, SECONDS, "per", second) \
  STATISTIC (propagations_backbone,  2, relative, "per", propagations) \
  STATISTIC (propagations_cover,     2, relative, "per", propagations) \
  STATISTIC (propagations_inst,      2, relative, "per", propagations) \
  STATISTIC (propagations_probe,     2, relative, "per", propagations) \
  STATISTIC (propagations_search,    2, relative, "per", propagations) \
  STATISTIC (propagations_transred,  2, relative, "per", propagations) \
  STATISTIC (propagations_vivify,    2, relative, "per", propagations) \
  STATISTIC (recomputed_tiers,       1, relative, "per", propagations) \
  STATISTIC (reduced,                1, relative, "per", propagations) \
  STATISTIC (reductions,             1, relative, "per", propagations) \
  STATISTIC (rephased,               1, relative, "per", propagations) \
  STATISTIC (rephased_best,          2, relative, "per", propagations) \
  STATISTIC (rephased_flipped,       2, relative, "per", propagations) \
  STATISTIC (rephased_inverted,      2, relative, "per", propagations) \
  STATISTIC (rephased_original,      2, relative, "per", propagations) \
  STATISTIC (rephased_random,        2, relative, "per", propagations) \
  STATISTIC (rephased_walk,          2, relative, "per", propagations) \
  STATISTIC (restart,                1, relative, "per", propagations) \
  STATISTIC (restart_levels,         2, relative, "per", propagations) \
  STATISTIC (restart_stable,         2, relative, "per", propagations) \
  STATISTIC (restorations,           1, relative, "per", propagations) \
  STATISTIC (restored_clauses,       1, relative, "per", propagations) \
  STATISTIC (restored_literals,      2, relative, "per", propagations) \
  STATISTIC (reused,                 1, relative, "per", propagations) \
  STATISTIC (reused_levels,          2, relative, "per", propagations) \
  STATISTIC (reused_stable,          2, relative, "per", propagations) \
  STATISTIC (scores_rescored,        2, relative, "per", propagations) \
  STATISTIC (scores_shuffled,        2, relative, "per", propagations) \
  STATISTIC (searches,               2, relative, "per", propagations) \
  STATISTIC (sections,               3, relative, "per", propagations) \
  STATISTIC (shrunken,               1, relative, "per", propagations) \
  STATISTIC (shrunken_minimize,      1, relative, "per", propagations) \
  STATISTIC (stable_conflicts,       2, relative, "per", propagations) \
  STATISTIC (stable_phases_current,  2, relative, "per", propagations) \
  STATISTIC (stable_phases_total,    1, relative, "per", propagations) \
  STATISTIC (strengthened,           1, relative, "per", propagations) \
  STATISTIC (subsume_checks,         2, relative, "per", propagations) \
  STATISTIC (subsume_checks_binary,  2, relative, "per", propagations) \
  STATISTIC (subsumed,               1, relative, "per", propagations) \
  STATISTIC (subsumed_irredundant,   2, relative, "per", propagations) \
  STATISTIC (subsumed_redundant,     2, relative, "per", propagations) \
  STATISTIC (subsume_phases,         2, relative, "per", propagations) \
  STATISTIC (subsume_rounds,         2, relative, "per", propagations) \
  STATISTIC (subsume_tried,          2, relative, "per", propagations) \
  STATISTIC (sweep,                  1, relative, "per", propagations) \
  STATISTIC (sweep_bb_fixed,         2, relative, "per", propagations) \
  STATISTIC (sweep_bb_flip,          2, relative, "per", propagations) \
  STATISTIC (sweep_bb_flipped,       2, relative, "per", propagations) \
  STATISTIC (sweep_bb_solved,        2, relative, "per", propagations) \
  STATISTIC (sweep_bb_solved_sat,    2, relative, "per", propagations) \
  STATISTIC (sweep_bb_solved_to,     2, relative, "per", propagations) \
  STATISTIC (sweep_bb_solved_unsat,  2, relative, "per", propagations) \
  STATISTIC (sweep_clauses,          2, relative, "per", propagations) \
  STATISTIC (sweep_completed,        2, relative, "per", propagations) \
  STATISTIC (sweep_depth,            2, relative, "per", propagations) \
  STATISTIC (sweep_environment,      2, relative, "per", propagations) \
  STATISTIC (sweep_eq,               1, relative, "per", propagations) \
  STATISTIC (sweep_eq_flip,          2, relative, "per", propagations) \
  STATISTIC (sweep_eq_flipped,       2, relative, "per", propagations) \
  STATISTIC (sweep_eq_solved,        2, relative, "per", propagations) \
  STATISTIC (sweep_eq_solved_sat,    2, relative, "per", propagations) \
  STATISTIC (sweep_eq_solved_to,     2, relative, "per", propagations) \
  STATISTIC (sweep_eq_solved_unsat,  2, relative, "per", propagations) \
  STATISTIC (sweep_solved,           2, relative, "per", propagations) \
  STATISTIC (sweep_solved_sat,       2, relative, "per", propagations) \
  STATISTIC (sweep_solved_unsat,     2, relative, "per", propagations) \
  STATISTIC (sweep_units,            1, relative, "per", propagations) \
  STATISTIC (sweep_variables,        2, relative, "per", propagations) \
  STATISTIC (ternary,                1, relative, "per", propagations) \
  STATISTIC (ternary_htrs,           1, relative, "per", propagations) \
  STATISTIC (ternary_htrs_binary,    2, relative, "per", propagations) \
  STATISTIC (ternary_htrs_ternary,   2, relative, "per", propagations) \
  STATISTIC (ternary_resolutions,    2, relative, "per", propagations) \
  STATISTIC (ticks,                  0, relative, "per", propagations) \
  STATISTIC (ticks_backbone,         2, relative, "per", propagations) \
  STATISTIC (ticks_factor,           2, relative, "per", propagations) \
  STATISTIC (ticks_probe,            2, relative, "per", propagations) \
  STATISTIC (ticks_search_stable,    2, relative, "per", propagations) \
  STATISTIC (ticks_search_unstable,  2, relative, "per", propagations) \
  STATISTIC (ticks_sweep,            2, relative, "per", propagations) \
  STATISTIC (ticks_ternary,          2, relative, "per", propagations) \
  STATISTIC (ticks_vivify,           2, relative, "per", propagations) \
  STATISTIC (ticks_walk,             2, relative, "per", propagations) \
  STATISTIC (ticks_walk_break,       2, relative, "per", propagations) \
  STATISTIC (ticks_walk_flip,        2, relative, "per", propagations) \
  STATISTIC (ticks_walk_flip_broke,  2, relative, "per", propagations) \
  STATISTIC (ticks_walk_flip_wl,     2, relative, "per", propagations) \
  STATISTIC (ticks_walk_pick,        2, relative, "per", propagations) \
  STATISTIC (transitive_clauses,     1, relative, "per", propagations) \
  STATISTIC (transitive_rounds,      2, relative, "per", propagations) \
  STATISTIC (transitive_units,       2, relative, "per", propagations) \
  STATISTIC (up_cb,                  2, relative, "per", propagations) \
  STATISTIC (up_cb_add,              1, relative, "per", propagations) \
  STATISTIC (up_cb_check_model,      1, relative, "per", propagations) \
  STATISTIC (up_cb_prop,             1, relative, "per", propagations) \
  STATISTIC (up_cb_prop_assign,      2, relative, "per", propagations) \
  STATISTIC (up_cb_prop_clash,       2, relative, "per", propagations) \
  STATISTIC (up_cb_prop_explain,     2, relative, "per", propagations) \
  STATISTIC (up_learn,               1, relative, "per", propagations) \
  STATISTIC (up_learn_conflict,      2, relative, "per", propagations) \
  STATISTIC (up_learn_elevating,     2, relative, "per", propagations) \
  STATISTIC (up_learn_empty,         2, relative, "per", propagations) \
  STATISTIC (up_learn_lazy_elevate,  2, relative, "per", propagations) \
  STATISTIC (up_learn_out_of_order,  2, relative, "per", propagations) \
  STATISTIC (up_learn_propagating,   2, relative, "per", propagations) \
  STATISTIC (up_learn_unit,          2, relative, "per", propagations) \
  STATISTIC (variables_extension,    2, relative, "per", propagations) \
  STATISTIC (variables_original,     1, relative, "per", propagations) \
  STATISTIC (vars,                   3, relative, "per", propagations) \
  STATISTIC (vars_active,            2, relative, "per", propagations) \
  STATISTIC (vars_all_elim,          2, relative, "per", propagations) \
  STATISTIC (vars_all_elim_fast,     2, relative, "per", propagations) \
  STATISTIC (vars_all_fixed,         2, relative, "per", propagations) \
  STATISTIC (vars_all_pure,          2, relative, "per", propagations) \
  STATISTIC (vars_all_substituted,   2, relative, "per", propagations) \
  STATISTIC (vars_bumped,            2, relative, "per", propagations) \
  STATISTIC (vars_declared,          2, relative, "per", propagations) \
  STATISTIC (vars_inactive,          2, relative, "per", propagations) \
  STATISTIC (vars_now_eliminated,    3, relative, "per", propagations) \
  STATISTIC (vars_now_fixed,         3, relative, "per", propagations) \
  STATISTIC (vars_now_pure,          3, relative, "per", propagations) \
  STATISTIC (vars_now_substituted,   3, relative, "per", propagations) \
  STATISTIC (vars_reactivated,       2, relative, "per", propagations) \
  STATISTIC (vars_unused,            2, relative, "per", propagations) \
  STATISTIC (vivifications,          1, relative, "per", propagations) \
  STATISTIC (vivified,               1, relative, "per", propagations) \
  STATISTIC (vivified_irr,           2, relative, "per", propagations) \
  STATISTIC (vivified_tier1,         2, relative, "per", propagations) \
  STATISTIC (vivified_tier2,         2, relative, "per", propagations) \
  STATISTIC (vivified_tier3,         2, relative, "per", propagations) \
  STATISTIC (vivify_checks,          2, relative, "per", propagations) \
  STATISTIC (vivify_decisions,       2, relative, "per", propagations) \
  STATISTIC (vivify_demote,          2, relative, "per", propagations) \
  STATISTIC (vivify_flushed,         2, relative, "per", propagations) \
  STATISTIC (vivify_implied,         2, relative, "per", propagations) \
  STATISTIC (vivify_instantiated,    2, relative, "per", propagations) \
  STATISTIC (vivify_reused,          2, relative, "per", propagations) \
  STATISTIC (vivify_scheduled,       2, relative, "per", propagations) \
  STATISTIC (vivify_strength,        2, relative, "per", propagations) \
  STATISTIC (vivify_strength_irr,    2, relative, "per", propagations) \
  STATISTIC (vivify_strength_tier1,  2, relative, "per", propagations) \
  STATISTIC (vivify_strength_tier2,  2, relative, "per", propagations) \
  STATISTIC (vivify_strength_tier3,  2, relative, "per", propagations) \
  STATISTIC (vivify_subsumed,        2, relative, "per", propagations) \
  STATISTIC (vivify_subsumed_irr,    2, relative, "per", propagations) \
  STATISTIC (vivify_subsumed_red,    2, relative, "per", propagations) \
  STATISTIC (vivify_units,           2, relative, "per", propagations) \
  STATISTIC (walk,                   1, relative, "per", propagations) \
  STATISTIC (walk_broken,            2, relative, "per", propagations) \
  STATISTIC (walk_flips,             2, relative, "per", propagations) \
  STATISTIC (walk_improved,          2, relative, "per", propagations) \
  STATISTIC (walk_sideways,          2, relative, "per", propagations) \
  STATISTIC (walk_warmup,            2, relative, "per", propagations) \
  STATISTIC (walk_warmup_conflicts,  2, relative, "per", propagations) \
  STATISTIC (walk_warmup_decision,   2, relative, "per", propagations) \
  STATISTIC (walk_warmup_dummy,      2, relative, "per", propagations) \
  STATISTIC (walk_warmup_propagate,  2, relative, "per", propagations) \
  STATISTIC (walk_weight_reducing,   2, relative, "per", propagations) \
  STATISTIC (walk_weight_transfer,   2, relative, "per", propagations) \
  STATISTIC (weakened,               1, relative, "per", propagations) \
  STATISTIC (weakened_lengths,       2, relative, "per", propagations)

// clang-format on

#endif
