#ifndef _statistics_h_INCLUDED
#define _statistics_h_INCLUDED

// clang-format off

//           NAME,    VERBOSITY (0-3), PRINTING
#define CADICAL_STATISTICS \
\
  STATISTIC (backbone_phases,                      1, relative, propagations, "per") \
  STATISTIC (backbone_probes,                      1, relative, propagations, "per") \
  STATISTIC (backbone_rounds,                      1, relative, propagations, "per") \
  STATISTIC (backbone_units,                       1, relative, propagations, "per") \
  STATISTIC (backtracked,                          3, relative, propagations, "per") \
  STATISTIC (blocked,                              1, relative, propagations, "per") \
  STATISTIC (blocked_candidates,                   1, relative, propagations, "per") \
  STATISTIC (blocked_pure,                         1, relative, propagations, "per") \
  STATISTIC (blocked_pure_literals,                1, relative, propagations, "per") \
  STATISTIC (blocked_resolutions,                  1, relative, propagations, "per") \
  STATISTIC (blockings,                            1, relative, propagations, "per") \
  STATISTIC (clauses_added_irredundant,            3, percent, clauses_added_total, "%") \
  STATISTIC (clauses_added_redundant,              3, relative, propagations, "per") \
  STATISTIC (clauses_added_total,                  3, relative, propagations, "per") \
  STATISTIC (clauses_current_irredundant,          3, relative, propagations, "per") \
  STATISTIC (clauses_current_redundant,            3, relative, propagations, "per") \
  STATISTIC (clauses_current_total,                3, relative, propagations, "per") \
  STATISTIC (clauses_improved_glue,                3, relative, propagations, "per") \
  STATISTIC (clauses_promoted_tier1,               3, relative, propagations, "per") \
  STATISTIC (clauses_promoted_tier2,               3, relative, propagations, "per") \
  STATISTIC (clauses_recomputed_glue,              3, relative, propagations, "per") \
  STATISTIC (collected,                            1, relative, propagations, "per") \
  STATISTIC (collections,                          1, relative, propagations, "per") \
  STATISTIC (compacts,                             1, relative, propagations, "per") \
  STATISTIC (condition_active,                     2, relative, propagations, "per") \
  STATISTIC (condition_candidates,                 2, relative, propagations, "per") \
  STATISTIC (conditioned,                          1, relative, propagations, "per") \
  STATISTIC (condition_final_assigned_init,        2, relative, propagations, "per") \
  STATISTIC (condition_final_assigned,             2, relative, propagations, "per") \
  STATISTIC (condition_final_autarky,              2, relative, propagations, "per") \
  STATISTIC (condition_final_conditional,          2, relative, propagations, "per") \
  STATISTIC (conditionings,                        2, relative, propagations, "per") \
  STATISTIC (condition_init_assigned,              2, relative, propagations, "per") \
  STATISTIC (condition_init_autarky,               2, relative, propagations, "per") \
  STATISTIC (condition_init_conditional,           2, relative, propagations, "per") \
  STATISTIC (condition_propagated,                 2, relative, propagations, "per") \
  STATISTIC (conflicts,                            0, relative, propagations, "per") \
  STATISTIC (conflicts_chrono,                     3, relative, propagations, "per") \
  STATISTIC (congruence_ands,                      1, relative, propagations, "per") \
  STATISTIC (congruence_dummy_ands,                1, relative, propagations, "per") \
  STATISTIC (congruence_gates,                     1, relative, propagations, "per") \
  STATISTIC (congruence_gates_and,                 1, relative, propagations, "per") \
  STATISTIC (congruence_gates_ite,                 1, relative, propagations, "per") \
  STATISTIC (congruence_gates_xor,                 1, relative, propagations, "per") \
  STATISTIC (congruence_ites,                      1, relative, propagations, "per") \
  STATISTIC (congruence_rewritten_ands,            1, relative, propagations, "per") \
  STATISTIC (congruence_rewritten_ites,            1, relative, propagations, "per") \
  STATISTIC (congruence_rewritten_xors,            1, relative, propagations, "per") \
  STATISTIC (congruence_rounds,                    1, INTERVAL, interval, "") \
  STATISTIC (congruence_simplified,                1, relative, propagations, "per") \
  STATISTIC (congruence_simplified_ands,           1, relative, propagations, "per") \
  STATISTIC (congruence_simplified_ites,           1, relative, propagations, "per") \
  STATISTIC (congruence_simplified_xors,           1, relative, propagations, "per") \
  STATISTIC (congruence_subsumed,                  1, relative, propagations, "per") \
  STATISTIC (congruence_trivial_ite,               1, relative, propagations, "per") \
  STATISTIC (congruence_unary,                     1, relative, propagations, "per") \
  STATISTIC (congruence_unary_and,                 1, relative, propagations, "per") \
  STATISTIC (congruence_unary_ite,                 1, relative, propagations, "per") \
  STATISTIC (congruence_units,                     1, relative, propagations, "per") \
  STATISTIC (congruence_xors,                      1, relative, propagations, "per") \
  STATISTIC (congruent,                            1, relative, propagations, "per") \
  STATISTIC (cover_asymmetric,                     2, relative, propagations, "per") \
  STATISTIC (cover_blocked,                        2, relative, propagations, "per") \
  STATISTIC (coverings,                            2, relative, propagations, "per") \
  STATISTIC (cover_total,                          2, relative, propagations, "per") \
  STATISTIC (decisions,                            0, relative, propagations, "per") \
  STATISTIC (decisions_random,                     1, relative, propagations, "per") \
  STATISTIC (decisions_random_phases,              1, relative, propagations, "per") \
  STATISTIC (decisions_searched,                   0, relative, propagations, "per") \
  STATISTIC (decompositions,                       1, relative, propagations, "per") \
  STATISTIC (deduplicated,                         1, relative, propagations, "per") \
  STATISTIC (deduplicate_init,                     1, relative, propagations, "per") \
  STATISTIC (deduplicate_init_rounds,              1, relative, propagations, "per") \
  STATISTIC (deduplicate_hyper_unary,              1, relative, propagations, "per") \
  STATISTIC (deduplications,                       1, relative, propagations, "per") \
  STATISTIC (eager_subsumed,                       1, relative, propagations, "per") \
  STATISTIC (eager_subsumtions,                    1, relative, propagations, "per") \
  STATISTIC (eliminate_and,                        1, relative, propagations, "per") \
  STATISTIC (eliminate_complete,                   1, relative, propagations, "per") \
  STATISTIC (eliminated,                           1, relative, propagations, "per") \
  STATISTIC (eliminated_and,                       1, relative, propagations, "per") \
  STATISTIC (eliminated_defs,                      1, relative, propagations, "per") \
  STATISTIC (eliminate_defs_checked,               1, relative, propagations, "per") \
  STATISTIC (eliminate_defs_extracted,             1, relative, propagations, "per") \
  STATISTIC (eliminate_defs_ticks,                 1, relative, propagations, "per") \
  STATISTIC (eliminate_defs_unit,                  1, relative, propagations, "per") \
  STATISTIC (eliminated_equivalence,               1, relative, propagations, "per") \
  STATISTIC (eliminated_ite,                       1, relative, propagations, "per") \
  STATISTIC (eliminated_xor,                       1, relative, propagations, "per") \
  STATISTIC (eliminate_equivalence,                1, relative, propagations, "per") \
  STATISTIC (eliminate_fast_phases,                1, relative, propagations, "per") \
  STATISTIC (eliminate_fast_rounds,                1, relative, propagations, "per") \
  STATISTIC (eliminate_gates,                      1, relative, propagations, "per") \
  STATISTIC (eliminate_ite,                        1, relative, propagations, "per") \
  STATISTIC (eliminate_otf_strengthened,           1, relative, propagations, "per") \
  STATISTIC (eliminate_otf_subsumed,               1, relative, propagations, "per") \
  STATISTIC (eliminate_phases,                     1, relative, propagations, "per") \
  STATISTIC (eliminate_resolved,                   1, relative, propagations, "per") \
  STATISTIC (eliminate_resolve_tried,              1, relative, propagations, "per") \
  STATISTIC (eliminate_strengthened_bw,            1, relative, propagations, "per") \
  STATISTIC (eliminate_substituted,                1, relative, propagations, "per") \
  STATISTIC (eliminate_subsumed_bw,                1, relative, propagations, "per") \
  STATISTIC (eliminate_tried,                      1, relative, propagations, "per") \
  STATISTIC (eliminate_xor,                        1, relative, propagations, "per") \
  STATISTIC (eliminations,                         1, relative, propagations, "per") \
  STATISTIC (extended,                             1, relative, propagations, "per") \
  STATISTIC (extensions,                           1, relative, propagations, "per") \
  STATISTIC (factor_added_clauses,                 1, relative, propagations, "per") \
  STATISTIC (factor_added_literals,                1, relative, propagations, "per") \
  STATISTIC (factored,                             1, relative, propagations, "per") \
  STATISTIC (factored_and,                         1, relative, propagations, "per") \
  STATISTIC (factored_eliminated,                  1, relative, propagations, "per") \
  STATISTIC (factored_ite,                         1, relative, propagations, "per") \
  STATISTIC (factored_xor,                         1, relative, propagations, "per") \
  STATISTIC (factorings,                           1, relative, propagations, "per") \
  STATISTIC (factor_removed_clauses,               1, relative, propagations, "per") \
  STATISTIC (factor_removed_literals,              1, relative, propagations, "per") \
  STATISTIC (factor_removed_redundant,             1, relative, propagations, "per") \
  STATISTIC (failed_literals,                      1, relative, propagations, "per") \
  STATISTIC (flush_hyper,                          2, relative, propagations, "per") \
  STATISTIC (flushings,                            2, relative, propagations, "per") \
  STATISTIC (flush_learned,                        2, relative, propagations, "per") \
  STATISTIC (garbage_bytes,                        1, relative, propagations, "per") \
  STATISTIC (garbage_clauses,                      1, relative, propagations, "per") \
  STATISTIC (garbage_literals,                     1, relative, propagations, "per") \
  STATISTIC (hbr_redundant,                        1, relative, propagations, "per") \
  STATISTIC (hbrs,                                 1, relative, propagations, "per") \
  STATISTIC (hbr_sizes,                            1, relative, propagations, "per") \
  STATISTIC (hbr_subsuming,                        1, relative, propagations, "per") \
  STATISTIC (ilb_reused_assumptions,               1, relative, propagations, "per") \
  STATISTIC (ilb_reused_levels,                    1, relative, propagations, "per") \
  STATISTIC (ilb_reused_literals,                  1, relative, propagations, "per") \
  STATISTIC (ilb_success,                          1, relative, propagations, "per") \
  STATISTIC (ilb_triggers,                         1, relative, propagations, "per") \
  STATISTIC (incremental_decay,                    1, relative, propagations, "per") \
  STATISTIC (inprobingphases,                      1, relative, propagations, "per") \
  STATISTIC (inprobingsuccess,                     1, relative, propagations, "per") \
  STATISTIC (instantiated,                         1, relative, propagations, "per") \
  STATISTIC (instantiate_tried,                    1, relative, propagations, "per") \
  STATISTIC (instantiations,                       1, relative, propagations, "per") \
  STATISTIC (irredundant_literals,                 1, relative, propagations, "per") \
  STATISTIC (learned_binaries,                     1, relative, propagations, "per") \
  STATISTIC (learned_clauses,                      1, relative, propagations, "per") \
  STATISTIC (learned_literals,                     1, relative, propagations, "per") \
  STATISTIC (learned_units,                        1, relative, propagations, "per") \
  STATISTIC (lucky,                                1, relative, propagations, "per") \
  STATISTIC (lucky_backward_one,                   2, relative, propagations, "per") \
  STATISTIC (lucky_backward_zero,                  2, relative, propagations, "per") \
  STATISTIC (lucky_constant_one,                   2, relative, propagations, "per") \
  STATISTIC (lucky_constant_zero,                  2, relative, propagations, "per") \
  STATISTIC (lucky_forward_one,                    2, relative, propagations, "per") \
  STATISTIC (lucky_forward_zero,                   2, relative, propagations, "per") \
  STATISTIC (lucky_random,                         2, relative, propagations, "per") \
  STATISTIC (lucky_tried,                          2, relative, propagations, "per") \
  STATISTIC (lucky_units,                          2, relative, propagations, "per") \
  STATISTIC (mark_block,                           3, relative, propagations, "per") \
  STATISTIC (mark_elim,                            3, relative, propagations, "per") \
  STATISTIC (mark_factor,                          3, relative, propagations, "per") \
  STATISTIC (mark_subsume,                         3, relative, propagations, "per") \
  STATISTIC (mark_ternary,                         3, relative, propagations, "per") \
  STATISTIC (minimized,                            1, relative, propagations, "per") \
  STATISTIC (otfs_strengthened,                    1, relative, propagations, "per") \
  STATISTIC (otfs_subsumed,                        1, relative, propagations, "per") \
  STATISTIC (preprocessings,                       1, relative, propagations, "per") \
  STATISTIC (probed,                               1, relative, propagations, "per") \
  STATISTIC (probe_failed_literals,                1, relative, propagations, "per") \
  STATISTIC (probingrounds,                        1, relative, propagations, "per") \
  STATISTIC (propagations,                         0, PER_SECOND, second, "per") \
  STATISTIC (propagations_backbone,                2, relative, propagations, "per") \
  STATISTIC (propagations_cover,                   2, relative, propagations, "per") \
  STATISTIC (propagations_instantiate,             2, relative, propagations, "per") \
  STATISTIC (propagations_probe,                   2, relative, propagations, "per") \
  STATISTIC (propagations_search,                  2, relative, propagations, "per") \
  STATISTIC (propagations_transred,                2, relative, propagations, "per") \
  STATISTIC (propagations_vivify,                  2, relative, propagations, "per") \
  STATISTIC (propagator_cb,                        1, relative, propagations, "per") \
  STATISTIC (propagator_cb_add,                    1, relative, propagations, "per") \
  STATISTIC (propagator_cb_check_model,            1, relative, propagations, "per") \
  STATISTIC (propagator_cb_propagate,              1, relative, propagations, "per") \
  STATISTIC (propagator_cb_propagate_assign,       2, relative, propagations, "per") \
  STATISTIC (propagator_cb_propagate_clash,        2, relative, propagations, "per") \
  STATISTIC (propagator_cb_propagate_explain,      2, relative, propagations, "per") \
  STATISTIC (propagator_learned,                   1, relative, propagations, "per") \
  STATISTIC (propagator_learned_conflict,          2, relative, propagations, "per") \
  STATISTIC (propagator_learned_elevating,         2, relative, propagations, "per") \
  STATISTIC (propagator_learned_empty,             2, relative, propagations, "per") \
  STATISTIC (propagator_learned_lazy_elevate,      2, relative, propagations, "per") \
  STATISTIC (propagator_learned_out_of_order,      2, relative, propagations, "per") \
  STATISTIC (propagator_learned_propagating,       2, relative, propagations, "per") \
  STATISTIC (propagator_learned_unit,              2, relative, propagations, "per") \
  STATISTIC (recomputed_tiers,                     1, relative, propagations, "per") \
  STATISTIC (reduced,                              1, relative, propagations, "per") \
  STATISTIC (reductions,                           1, relative, propagations, "per") \
  STATISTIC (rephased,                             1, relative, propagations, "per") \
  STATISTIC (rephased_best,                        2, relative, propagations, "per") \
  STATISTIC (rephased_flipped,                     2, relative, propagations, "per") \
  STATISTIC (rephased_inverted,                    2, relative, propagations, "per") \
  STATISTIC (rephased_original,                    2, relative, propagations, "per") \
  STATISTIC (rephased_random,                      2, relative, propagations, "per") \
  STATISTIC (rephased_walk,                        2, relative, propagations, "per") \
  STATISTIC (restart,                              1, relative, propagations, "per") \
  STATISTIC (restart_levels,                       3, relative, propagations, "per") \
  STATISTIC (restart_stable,                       3, relative, propagations, "per") \
  STATISTIC (restorations,                         1, relative, propagations, "per") \
  STATISTIC (restored_clauses,                     1, relative, propagations, "per") \
  STATISTIC (restored_literals,                    1, relative, propagations, "per") \
  STATISTIC (reused,                               1, relative, propagations, "per") \
  STATISTIC (reused_levels,                        1, relative, propagations, "per") \
  STATISTIC (reused_stable,                        1, relative, propagations, "per") \
  STATISTIC (scores_rescored,                      1, relative, propagations, "per") \
  STATISTIC (scores_shuffled,                      1, relative, propagations, "per") \
  STATISTIC (searches,                             2, relative, propagations, "per") \
  STATISTIC (sections,                             3, relative, propagations, "per") \
  STATISTIC (shrunken,                             1, relative, propagations, "per") \
  STATISTIC (shrunken_minimize,                    1, relative, propagations, "per") \
  STATISTIC (stable_conflicts,                     2, relative, propagations, "per") \
  STATISTIC (stable_phases_incremental,            2, relative, propagations, "per") \
  STATISTIC (stable_phases_total,                  1, relative, propagations, "per") \
  STATISTIC (strengthened,                         1, relative, propagations, "per") \
  STATISTIC (subsume_checks,                       1, relative, propagations, "per") \
  STATISTIC (subsume_checks_binary,                1, relative, propagations, "per") \
  STATISTIC (subsumed,                             1, relative, propagations, "per") \
  STATISTIC (subsumed_irredundant,                 1, relative, propagations, "per") \
  STATISTIC (subsumed_redundant,                   1, relative, propagations, "per") \
  STATISTIC (subsume_phases,                       1, relative, propagations, "per") \
  STATISTIC (subsume_rounds,                       1, relative, propagations, "per") \
  STATISTIC (subsume_tried,                        1, relative, propagations, "per") \
  STATISTIC (sweep,                                1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_fixed,                 1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_flip,                  1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_flipped,               1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_solved,                1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_solved_sat,            1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_solved_unknown,        1, relative, propagations, "per") \
  STATISTIC (sweep_backbone_solved_unsat,          1, relative, propagations, "per") \
  STATISTIC (sweep_clauses,                        1, relative, propagations, "per") \
  STATISTIC (sweep_completed,                      1, relative, propagations, "per") \
  STATISTIC (sweep_depth,                          1, relative, propagations, "per") \
  STATISTIC (sweep_environment,                    1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences,                   1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences_flip,              1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences_flipped,           1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences_solved,            1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences_solved_sat,        1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences_solved_unknown,    1, relative, propagations, "per") \
  STATISTIC (sweep_equivalences_solved_unsat,      1, relative, propagations, "per") \
  STATISTIC (sweep_solved,                         1, relative, propagations, "per") \
  STATISTIC (sweep_solved_sat,                     1, relative, propagations, "per") \
  STATISTIC (sweep_solved_unsat,                   1, relative, propagations, "per") \
  STATISTIC (sweep_units,                          1, relative, propagations, "per") \
  STATISTIC (sweep_variables,                      1, relative, propagations, "per") \
  STATISTIC (ternary,                              1, relative, propagations, "per") \
  STATISTIC (ternary_htrs,                         1, relative, propagations, "per") \
  STATISTIC (ternary_htrs_binary,                  1, relative, propagations, "per") \
  STATISTIC (ternary_htrs_ternary,                 1, relative, propagations, "per") \
  STATISTIC (ternary_resolutions,                  1, relative, propagations, "per") \
  STATISTIC (ticks,                                0, relative, propagations, "per") \
  STATISTIC (ticks_backbone,                       2, relative, propagations, "per") \
  STATISTIC (ticks_factor,                         2, relative, propagations, "per") \
  STATISTIC (ticks_probe,                          2, relative, propagations, "per") \
  STATISTIC (ticks_search_stable,                  2, relative, propagations, "per") \
  STATISTIC (ticks_search_unstable,                2, relative, propagations, "per") \
  STATISTIC (ticks_sweep,                          2, relative, propagations, "per") \
  STATISTIC (ticks_ternary,                        2, relative, propagations, "per") \
  STATISTIC (ticks_vivify,                         2, relative, propagations, "per") \
  STATISTIC (ticks_walk,                           2, relative, propagations, "per") \
  STATISTIC (ticks_walk_break,                     2, relative, propagations, "per") \
  STATISTIC (ticks_walk_flip,                      2, relative, propagations, "per") \
  STATISTIC (ticks_walk_flip_broken,               2, relative, propagations, "per") \
  STATISTIC (ticks_walk_flip_wl,                   2, relative, propagations, "per") \
  STATISTIC (ticks_walk_pick,                      2, relative, propagations, "per") \
  STATISTIC (transitive_rounds,                    1, relative, propagations, "per") \
  STATISTIC (transitive_clauses,                   1, relative, propagations, "per") \
  STATISTIC (transitive_units,                     1, relative, propagations, "per") \
  STATISTIC (variables_extension,                  1, relative, propagations, "per") \
  STATISTIC (variables_original,                   1, relative, propagations, "per") \
  STATISTIC (vars,                                 2, relative, propagations, "per") \
  STATISTIC (vars_active,                          1, relative, propagations, "per") \
  STATISTIC (vars_all_eliminated,                  1, relative, propagations, "per") \
  STATISTIC (vars_all_eliminated_fast,             1, relative, propagations, "per") \
  STATISTIC (vars_all_fixed,                       1, relative, propagations, "per") \
  STATISTIC (vars_all_pure,                        1, relative, propagations, "per") \
  STATISTIC (vars_all_substituted,                 1, relative, propagations, "per") \
  STATISTIC (vars_bumped,                          3, relative, propagations, "per") \
  STATISTIC (vars_declared,                        1, relative, propagations, "per") \
  STATISTIC (vars_inactive,                        1, relative, propagations, "per") \
  STATISTIC (vars_now_eliminated,                  1, relative, propagations, "per") \
  STATISTIC (vars_now_fixed,                       1, relative, propagations, "per") \
  STATISTIC (vars_now_pure,                        1, relative, propagations, "per") \
  STATISTIC (vars_now_substituted,                 1, relative, propagations, "per") \
  STATISTIC (vars_reactivated,                     1, relative, propagations, "per") \
  STATISTIC (vars_unused,                          1, relative, propagations, "per") \
  STATISTIC (vivifications,                        1, relative, propagations, "per") \
  STATISTIC (vivified,                             1, relative, propagations, "per") \
  STATISTIC (vivified_irredundant,                 1, relative, propagations, "per") \
  STATISTIC (vivified_redundant_tier1,             1, relative, propagations, "per") \
  STATISTIC (vivified_redundant_tier2,             1, relative, propagations, "per") \
  STATISTIC (vivified_redundant_tier3,             1, relative, propagations, "per") \
  STATISTIC (vivify_checks,                        1, relative, propagations, "per") \
  STATISTIC (vivify_decisions,                     1, relative, propagations, "per") \
  STATISTIC (vivify_demote,                        1, relative, propagations, "per") \
  STATISTIC (vivify_flushed,                       1, relative, propagations, "per") \
  STATISTIC (vivify_implied,                       1, relative, propagations, "per") \
  STATISTIC (vivify_instantiated,                  1, relative, propagations, "per") \
  STATISTIC (vivify_reused,                        1, relative, propagations, "per") \
  STATISTIC (vivify_scheduled,                     1, relative, propagations, "per") \
  STATISTIC (vivify_strengthened,                  1, relative, propagations, "per") \
  STATISTIC (vivify_strengthened_irredundant,      1, relative, propagations, "per") \
  STATISTIC (vivify_strengthened_redundant_tier1,  1, relative, propagations, "per") \
  STATISTIC (vivify_strengthened_redundant_tier2,  1, relative, propagations, "per") \
  STATISTIC (vivify_strengthened_redundant_tier3,  1, relative, propagations, "per") \
  STATISTIC (vivify_subsumed,                      1, relative, propagations, "per") \
  STATISTIC (vivify_subsumed_irredundant,          1, relative, propagations, "per") \
  STATISTIC (vivify_subsumed_redundant,            1, relative, propagations, "per") \
  STATISTIC (vivify_units,                         1, relative, propagations, "per") \
  STATISTIC (walk,                                 1, relative, propagations, "per") \
  STATISTIC (walk_broken,                          2, relative, propagations, "per") \
  STATISTIC (walk_flips,                           2, relative, propagations, "per") \
  STATISTIC (walk_improved,                        2, relative, propagations, "per") \
  STATISTIC (walk_sideways,                        2, relative, propagations, "per") \
  STATISTIC (walk_warmup,                          2, relative, propagations, "per") \
  STATISTIC (walk_warmup_conflicts,                2, relative, propagations, "per") \
  STATISTIC (walk_warmup_decision,                 2, relative, propagations, "per") \
  STATISTIC (walk_warmup_decision_dummy,           2, relative, propagations, "per") \
  STATISTIC (walk_warmup_propagated,               2, relative, propagations, "per") \
  STATISTIC (walk_weight_reducing,                 2, relative, propagations, "per") \
  STATISTIC (walk_weight_transfer,                 2, relative, propagations, "per") \
  STATISTIC (weakened,                             1, relative, propagations, "per") \
  STATISTIC (weakened_lengths,                     1, relative, propagations, "per")

// clang-format on

#endif
